---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r load_libraries}
library(tidyverse)
library(lubridate)
library(leaflet)
library(htmltools)
library(MSDR)
```

```{r}
file_path <- system.file("extdata", "signif.tsv", package = "MSDR")
signif <- read_tsv(file_path) %>%
  eq_clean_date %>%
  eq_clean_location
```

```{r}

```

```{r}
signif %>%
  filter(COUNTRY == 'MEXICO') %>%
  ggplot(aes(date = date,
               xmin = as.Date('1990-09-22'),
               xmax = as.Date('2000-12-05'),
               y = COUNTRY,
               colour = DEATHS,
               fill = DEATHS,
               size = EQ_PRIMARY,
               location = LOCATION)) +
  geom_timeline() +
  geom_timeline_label() +
  theme_timeline
```


# maps

```{r}
signif %>%
  filter(COUNTRY == 'MEXICO' & year(date) >= 2000) %>%
  mutate(popup_text = eq_create_label(.)) %>%
  eq_map()
```

